image: docker:19.03.12

stages:
  - build image
  - build project
  - push to github

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  JOMIGU_NODE_IMAGE: tsiminiya/jomigu-website-builder:${CI_COMMIT_REF_NAME}
  BACKUP_JOMIGU_NODE_IMAGE: tsiminiya/jomigu-website-builder:${CI_COMMIT_REF_NAME}
  JOMIGU_WEBSITE_REPO: https://tsiminiya:${GITHUB_ACCESS_TOKEN}@github.com/tsiminiya/jomigu.git

services:
  - docker:19.03.12-dind

build:image:
  stage: build image
  image: docker:dind
  before_script:
    - docker login -u tsiminiya -p $DOCKER_ACCESS_TOKEN
  script:
    - docker build ${PWD} -t tsiminiya/jomigu-website-builder:${CI_COMMIT_REF_NAME}
    - docker push ${BACKUP_JOMIGU_NODE_IMAGE}
    - docker tag ${BACKUP_JOMIGU_NODE_IMAGE} ${JOMIGU_NODE_IMAGE}
    - docker push ${JOMIGU_NODE_IMAGE}
  only:
    changes:
      - Dockerfile

build:project:
  stage: build project
  image: ${JOMIGU_NODE_IMAGE}
  script:
    - git remote set-url origin ${JOMIGU_WEBSITE_REPO}
    - git fetch
    - git checkout main
    - git pull
    - npm install
    - npm run generate
    - git reset --hard
    - npm run deploy
  artifacts:
    paths:
      - dist
    expire_in: 30 days
  only:
    refs:
      - main
